language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_548bcd8e080e_key -iv $encrypted_548bcd8e080e_iv
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties
  -d
