language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_48263c15126f_key -iv $encrypted_48263c15126f_iv
  -in application.properties.enc -out src/main/resources/application.properties -d
