language: java
jdk:
- oraclejdk8
before_install:
dd:
  secure: APN6sPeCHpeI6pmWF+QqVlzO360HVr7BRQ4SWDODbsP+NkTISj5/FiNNzqeXvp547KeFAeMQK3PCWE6IJAjpjialdW/tBWNjRhVG0ZNgux8gaTMWpfgBCjBcCfyg7R+lSWyHrSW+tNlAT144wT7NFzIaq1lGD5MJ0JMuciM10BQpWEv1iP9TVoFnn9/+A01N93izo9Fr8wF91pgemVCblV1czPuVQPfGUs1Og0sIZvT2E915MNKgjePCL09TqSQydEfJ2UTSseqe1tnVpiAJWJOr7d1lftc+WVv2sqVDoIl8zBrnDh+5iged6A/KcxaR9h1UXllH6U7/m4gR6NAJ+xe7Y3p3rjP3JZuRIfApywV/ygdJ/PvogYYqLvFoj7AYmE6MFVfPhYpGWaqjjMnrvuE0TR1Q/fKn9c70rYo6rAgjjdDkYYFRE8abD1gmaKfbqEhDe5lIry1DK3HOL/KYf3PT3Apr0L39wgD0xRe2h2v/GXHWwVsusmpEnqWLNcI8jjOCTZmrixK44pM/QEU2gKEAI3sUKl0ugSUZM4JKUo05+lVFHcXq1dGaIEbjlBpfJOFBvpCKAGoVP6oNudJwW2mZ6pwKbHuCSwakzQvcuspzLQVz1bD6UHB/0eECVlfKKJh8gR9bvtvzMQwdyouj4I0Ie3mQjUh9a/jYodaoq2I=
