language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_a60d796c1930_key -iv $encrypted_a60d796c1930_iv
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties
  -d
